// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMAWrqVN6rLpkUshBCbHUgXMQCBoM19MI',
    appId: '1:496163842918:web:f011ddeda47f7b53ef36a7',
    messagingSenderId: '496163842918',
    projectId: 'e-commerce-a5859',
    authDomain: 'e-commerce-a5859.firebaseapp.com',
    storageBucket: 'e-commerce-a5859.appspot.com',
    measurementId: 'G-E5VYQJ47Q4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYNFJPZlBW9BICNju23sTzjmB3PL8l5KI',
    appId: '1:496163842918:android:4fa62c4495749585ef36a7',
    messagingSenderId: '496163842918',
    projectId: 'e-commerce-a5859',
    storageBucket: 'e-commerce-a5859.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKwgkRJslgqR35h7_45fwVC2iBBtNnPlI',
    appId: '1:496163842918:ios:fba40373cba2f97aef36a7',
    messagingSenderId: '496163842918',
    projectId: 'e-commerce-a5859',
    storageBucket: 'e-commerce-a5859.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKwgkRJslgqR35h7_45fwVC2iBBtNnPlI',
    appId: '1:496163842918:ios:ed76b9aa2b99c8a8ef36a7',
    messagingSenderId: '496163842918',
    projectId: 'e-commerce-a5859',
    storageBucket: 'e-commerce-a5859.appspot.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
